name: mediconnect
description: AI-powered Health Assistant for Rural & Underserved Communities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  # google_fonts: ^6.1.0
  intl: ^0.18.1
  uuid: ^4.2.2
  speech_to_text: ^6.6.0
  http: ^1.1.0
  image_picker: ^1.0.4
  google_maps_flutter: ^2.6.0
  url_launcher: ^6.2.2
  web3dart: ^2.7.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
